pipeline {
    agent any
    // Ensure these tool names match your configuration in Manage Jenkins -> Global Tool Configuration
    tools {
        maven 'M3' 
        jdk 'JDK17' 
    }
    environment {
         // Define URLs directly, as they are not secrets
        NEXUS_REPO_HOST = 'http://localhost:8081' // REPLACE with your actual Nexus URL from GITHUB_URL
        SONAR_URL = 'http://localhost:9000' // REPLACE with your actual SonarQube URL from SONAR_HOST_URL

        // Reference the *Jenkins Credential IDs* we created in Step 1
        NEXUS_CREDS_ID = 'admin'       // <-- Must match Jenkins ID
        SONAR_TOKEN_ID = 'oysheeb19'   // <-- Must match Jenkins ID
        
        NEXUS_SNAPSHOT_REPO = 'maven-snapshots'
        NEXUS_RELEASE_REPO = 'maven-releases'
    }
    stages {
        stage('Checkout Code') {
            steps {
                // Check out the code from the SCM defined in the job configuration
                checkout scm
            }
        }
        stage('Build and Unit Test') {
            steps {
                // Use the pom.xml to compile, test, and package the artifact
                sh 'mvn clean install' 
            }
        }
        stage('Sonar Test/Analysis') {
            steps {
                // Use the SonarQube Scanner defined in Global Tool Configuration (installationName: 'sonarscanner')
                withSonarQubeEnv(credentialsId: env.SONAR_TOKEN_ID, installationName: 'sonarscanner') {
                    // Use the project key from your SonarQube server configuration
                    sh 'mvn sonar:sonar -Dsonar.projectKey=ci-cd-dummy -Dsonar.host.url=${SONAR_URL}'
                }
            }
        }
        stage('Publish Artifact to Nexus') {
            steps {
                script {
                    // Read the GAVC details dynamically from the project's pom.xml file
                    def pom = readMavenPom file: 'pom.xml'
                    
                    // Determine if this is a SNAPSHOT or RELEASE version to choose the correct Nexus repo
                    def repoName = pom.version.contains('SNAPSHOT') ? env.NEXUS_SNAPSHOT_REPO : env.NEXUS_RELEASE_REPO
                    
                    echo "Uploading artifact version ${pom.version} to Nexus repository: ${repoName}"

                    // Use the Nexus Artifact Uploader Plugin step
                    nexusArtifactUploader(
                        nexusVersion: 'nexus3',
                        protocol: 'http',
                        nexusUrl: env.NEXUS_REPO_HOST,
                        repository: repoName,
                        credentialsId: env.NEXUS_CREDS_ID,
                        groupId: pom.groupId,
                        artifactId: pom.artifactId,
                        version: pom.version,
                        packaging: pom.packaging, // Uses 'jar' as defined in your POM
                        // Specify the actual file path generated by the 'mvn clean install' command
                        artifacts: [[artifactId: pom.artifactId, classifier: '', file: "target/${pom.artifactId}-${pom.version}.jar", type: pom.packaging]]
                    )
                }
            }
        }
    }
}